### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by enes-usta** [enes-usta/bgp-filter#4]
- [x] Reformat JSON output

- [x] Add --noail option to disable publishing to ail
- [x] Re add --json-output for custom file output
- [x] AS Number can be != 5 digits number
 - [x] File caching using [Redis](<https://github.com/redis/redis-py>)
   - [x] Load config
   - [x] Check if elem is already saved
   - [x] Save
   - [x] Expiration
- [x] Accept single data source file
- [x] Generate datasets for testing
 - [x] Add --queue option
- [ ] Use Redis stream instead of redis
 - [ ] Send json output to ai using [PyAil](<https://github.com/ail-project/PyAIL>)
   - [x] Load config
   - [x] Create request
   - [ ] Retrieve in ail
